[tox]
envlist = pre-commit,py,docs-lint,docs-all
skip_missing_interpreters = True

[testenv:pre-commit]
package = wheel
wheel_build_env = .pkg
dependency_groups = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure --color=always

[testenv:py]
package = wheel
wheel_build_env = .pkg
depends: pre-commit
dependency_groups = test
commands =
    python -X warn_default_encoding -m pytest {posargs:-vv --color yes}
    cov  : python -X warn_default_encoding -m coverage run -m pytest {posargs:-vv --color yes}
    fast : python -m pytest {posargs:-vv --color yes -n auto}


[docs]
docs_dir = {tox_root}{/}docs
shared_content_dir = {tox_root}{/}src{/}beeware_docs_tools{/}shared_content
templates_dir = {tox_root}{/}docs{/}locales{/}templates

[testenv:docs{,-translate,-lint,-en,-ar,-cs,-da,-de,-es,-fa,-fr,-it,-ja,-ko,-pl,-pt,-ru,-tr,-vi,-zh_CN,-zh_TW,-all,-serve,-live}]
# Docs are always built on Python 3.13. See also the RTD config.
base_python = py313
skip_install = true
setenv =
    DISABLE_MKDOCS_2_WARNING = true
    NO_MKDOCS_2_WARNING = 1
passenv =
    DEEPL_API_KEY
    READTHEDOCS_CANONICAL_URL
deps =
    -e .
commands:
    !translate-!lint-!en-!ar-!cs-!da-!de-!es-!fa-!fr-!it-!ja-!ko-!pl-!pt-!ru-!tr-!vi-!zh_CN-!zh_TW-!all-!serve-!live : build_md_translations {posargs} --source-code=src en
    translate : build_pot_translations
    translate : build_po_translations ar cs da de es fa fr it ja ko pl pt ru tr vi zh_CN zh_TW
    translate : update_machine_translations --soft-fail ar cs da de es fa fr it ja ko pl pt ru tr vi zh_CN zh_TW
    # Docs-tools also includes shared content, which is used by downstream repositories.
    # Do an additional translation pass on that content.
    translate : build_pot_translations -d {[docs]shared_content_dir}
    translate : build_po_translations ar cs da de es fa fr it ja ko pl pt ru tr vi zh_CN zh_TW -d {[docs]shared_content_dir}
    translate : update_machine_translations --soft-fail -d {[docs]shared_content_dir} ar cs da de es fa fr it ja ko pl pt ru tr vi zh_CN zh_TW
    lint : pyspelling
    lint : markdown-checker --dir {[docs]docs_dir} --func check_broken_urls
    lint : markdown-checker --dir {[docs]shared_content_dir} --func check_broken_urls "--skip-urls-containing=https://app.readthedocs.org/projects/{{ project_name }}/,https://github.com/beeware/{{ project_name }},https://example.com/"
    en : build_md_translations {posargs} --source-code=src en
    ar : build_md_translations {posargs} --source-code=src ar
    cs : build_md_translations {posargs} --source-code=src cs
    da : build_md_translations {posargs} --source-code=src da
    de : build_md_translations {posargs} --source-code=src de
    es : build_md_translations {posargs} --source-code=src es
    fa : build_md_translations {posargs} --source-code=src fa
    fr : build_md_translations {posargs} --source-code=src fr
    it : build_md_translations {posargs} --source-code=src it
    ja : build_md_translations {posargs} --source-code=src ja
    ko : build_md_translations {posargs} --source-code=src ko
    pl : build_md_translations {posargs} --source-code=src pl
    pt : build_md_translations {posargs} --source-code=src pt
    ru : build_md_translations {posargs} --source-code=src ru
    tr : build_md_translations {posargs} --source-code=src tr
    vi : build_md_translations {posargs} --source-code=src vi
    zh_CN : build_md_translations {posargs} --source-code=src zh_CN
    zh_TW : build_md_translations {posargs} --source-code=src zh_TW
    all : build_md_translations {posargs} --source-code=src en ar cs da de es fa fr it ja ko pl pt ru tr vi zh_CN zh_TW
    serve : python -m http.server -d _build/html 8037
    live : live_serve_en {posargs} src --port=8037 --source-code=src
