import subprocess
from argparse import ArgumentParser, Namespace
from pathlib import Path
from tempfile import TemporaryDirectory

import polib
import yaml

from .md_tempdir import process_nav

# This tool is used to generate PO template (POT) files from English Markdown
# content.
#
# The Markdown content can optionally contain external shared content included
# using the PyMdown Snippets extension. To facilitate translation of the shared
# content, it is included as part of BeeWare Docs Tools, along with the
# associated `locales` directory containing the shared content POT and
# translated PO files. This content is then processed separately from the
# primary content, and the resulting files are stored within the `docs-tools`
# repo `src` directory. When BeeWare Docs Tools is installed into a
# documentation repo, it includes the shared Markdown and PO files. They are
# then made available to the other translation- and build-tools, so when they
# are run, they are able to access the translated shared content and build each
# translated site in a given language.


def parse_args() -> Namespace:
    parser = ArgumentParser()
    parser.add_argument("-d", "--docs-directory", type=Path, default="docs")
    parser.add_argument("-x", "--exclude", action="append", type=Path, default=[])
    args = parser.parse_args()

    return args


def generate_titles(docs: Path) -> None:
    try:
        with (docs / "config.yml").open() as f:
            config = yaml.load(f, Loader=yaml.SafeLoader)

        en_titles = []

        def accumulate(entry):
            en_titles.append(entry)

        process_nav(config["nav"], accumulate)

        title_file = docs / "en/titles.md"
        title_file.write_text(
            "<!-- generated by build_pot_translations.py -->\n\n"
            + "\n\n".join(en_titles)
        )
        return title_file
    except FileNotFoundError:
        # "No config.yml file
        pass
    except KeyError:
        # No navigation in config.
        pass


def markdown_to_pot(docs: Path, working_path: Path, excludes: list[Path]) -> None:
    """
    Run `md2po` with provided input and output directories, with `--pot` flag to
    generate PO template (POT) files.

    When invoking `md2po`:

    * `--duplicates=merge` enforces multiple copies of the same string being
      shown once with multiple locations.
    * `--timestamp` ensures that new files are only generated when there is new
      content.

    :param docs: The directory fragment, relative to the root path, containing
        the `en` Markdown content and `locales` translation files directories.
    :param working_path: The directory considered `/` for the input file call.
        This ensures that the location strings are accurate in the POT and PO
        files.
    """
    output_path = Path.cwd() / docs / "locales/template/translations.pot"

    # Ensure the output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # If the pot file already exists, delete it. Pre-existing pot files cause
    # havoc around what ends up in the final pot file.
    if output_path.exists():
        output_path.unlink()

    # Generate the new pot file
    md2po_command = [
        "md2po",
        f"--input={docs / 'en'}",
        f"--output={output_path}",
        "--pot",
        "--timestamp",
        "--duplicates=merge",
        "--multifile=onefile",
    ] + [f"--exclude={p}" for p in excludes]

    subprocess.run(
        md2po_command,
        check=True,
        cwd=working_path,
    )

    # Resave with a long wrap width to remove word wraps.
    po = polib.pofile(output_path, wrapwidth=100000)
    po.save(output_path)


def generate_pot_files(docs: Path, excludes: list[Path]) -> None:
    """
    Generate the PO template (POT) files for the content in the provided
    directory.

    :param docs: The directory fragment, relative to the root path, containing
        the `en` Markdown content and `locales` translation files directories.
        This will become the msg* string location prefix in the generated POT
        files.
    """
    with TemporaryDirectory() as temp_working_directory:
        temp_working_path = Path(temp_working_directory)

        (temp_working_path / docs).parent.mkdir(parents=True, exist_ok=True)

        try:
            (temp_working_path / docs).symlink_to(
                Path.cwd() / docs,
                target_is_directory=True,
            )
        except FileExistsError:
            pass

        title_file = generate_titles(docs)

        markdown_to_pot(docs=docs, working_path=temp_working_path, excludes=excludes)

        if title_file:
            title_file.unlink()


def main():
    args = parse_args()
    # Generate POT files.
    generate_pot_files(
        args.docs_directory.resolve().relative_to(Path.cwd()), args.exclude
    )


if __name__ == "__main__":
    main()
